---
title: "R Notebook"
output: html_notebook
---

```{r}
packages = c('ggmap', 'ggplot2', 'tmap', 'sf', 'rgdal', 'maptools', 'spatstat')
for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```

```{r}
library(ggmap)
library(ggplot2)
library(tmap)
library(sf)
firms <- read.csv("data/geocodedCombined.csv", stringsAsFactors = FALSE)
firms <- subset(firms,type>="Legal")
```

```{r}
firms_shp <- st_as_sf(firms, coords = c("lon", "lat"), crs = 4326)
firms_shp<-st_transform(firms_shp, 3414)
firms_sp1 = as(firms_shp, 'Spatial')
firms_sp2 = as(firms_sp1, 'SpatialPoints')
#firms_sp2 <- spTransform(firms_sp2, CRS("+proj=longlat +lat_0=1.366666666666667 +lon_0=103.8333333333333 +k=1
#+x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +units=m +no_defs"))
```

```{r}
subzones <- readOGR(dsn="shp/master-plan-2014-subzone-boundary-no-sea", layer="MP14_SUBZONE_NO_SEA_PL")
```

```{r}
subzone_cr <- subzones[subzones$REGION_C == "CR",]
cr_sp = as(subzone_cr, 'SpatialPolygons')
plot(cr_sp)
#subzone_cr <- spTransform(subzone_cr, CRS("+proj=longlat +lat_0=1.366666666666667 +lon_0=103.8333333333333 +k=1
#+x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +units=m +no_defs"))
#crs_1 <- crs(subzone_cr)
#subzone_cr <- spTransform(subzone_cr, CRS(paste(crs_1)))
#firms_sp2 <- coordinates(spTransform(firms_sp2, CRS(crs_1)))
#subzone_cr <- spTransform(subzone_cr, crs(firms_sp3))
#cr_sp <- spTransform(cr_sp, crs(firms_sp3))
```

```{r}
cr_owin <- as.owin.SpatialPolygons(cr_sp)
plot(cr_owin)
```

```{r}
point.ppp <- ppp(coordinates(firms_sp2)[,1], coordinates(firms_sp2)[,2], window = cr_owin)
plot(point.ppp)
```

```{r}
#K <- envelope(point.ppp, Kest, nsim = 3)
K <- Kest(point.ppp)
plot(K)
```

```{r}
library(raster)
kde_sp_100 <- density(point.ppp, 280)
plot(kde_sp_100)
```

```{r}
library(tmap)
library(tmaptools)
temp_sgdf <- as(kde_sp_100, 'SpatialPolygons')
proj4string(temp_sgdf) <- CRS("+proj=tmerc +lat_0=1.366666666666667 +lon_0=103.8333333333333 +k=1 +x_0=28001.642 +y_0=38744.572
+datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0")
qtm(temp_sgdf)
#tmap_mode("view")
#tm_shape(raster(kde_sp_100)) +
  #tm_raster()
```

```{r}
r<-raster(kde_sp_100)
proj4string(r) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
ggmap(SGMap) + geom_point(aes(x = x, y = y, colour = r), data = r) +
  ggtitle("Professional services using KMean")
```

