---
title: "kmeans"
output: html_document
---


```{r}
library(sp)
library(rgdal)
library(geosphere)
library(tidyverse)
```


```{r}
industries <- read_csv("geocodedCombined.csv")
```

```{r}
x <- industries$lon
y <- industries$lat

```

```{r}
# convert data to a SpatialPointsDataFrame object
xy <- SpatialPointsDataFrame(
      matrix(c(x,y), ncol=2), data.frame(ID=seq(1:length(x))),
      proj4string=CRS("+proj=longlat +init=EPSG:3414 +ellps=WGS84 +units=m
+no_defs"))
summary(xy)
```

```{r}
# use the distm function to generate a geodesic distance matrix in meters
mdist <- distm(xy)
```

```{r}
# cluster all points using a hierarchical clustering approach
set.seed(20)
km <- kmeans(as.dist(mdist), 5, nstart = 20)
# hc <- hclust(as.dist(mdist), method = "complete")
```

```{r}
table(km$cluster, industries$type)

#d=40
#xy$clust <- cutree(hc, h=d)
#table(xy$clust, industries$type)
#str(km)
```

# for hier do not think is necessary
```{r}
# #library(dismo)
# #library(rgeos)
# 
# # expand the extent of plotting frame
# #xy@bbox[] <- as.matrix(extend(extent(xy),0.001))
# 
# # get the centroid coords for each cluster
# #cent <- matrix(ncol=2, nrow=max(xy$clust))
# for (i in 1:max(xy$clust))
#     # gCentroid from the rgeos package
#     cent[i,] <- gCentroid(subset(xy, clust == i))@coords
# 
# # compute circles around the centroid coords using a 40m radius
# # from the dismo package
# ci <- circles(cent, d=d, lonlat=T)
# 
# # plot
# plot(ci@polygons, axes=T)
# plot(xy, col=rainbow(5)[factor(xy$clust)], add=T)
```

```{r}
library(ggmap)
#test plot on sg map
SGMap <- get_map(location = "singapore", zoom = 10, source = "google")
industries$clust <- as.factor(km$cluster)
ggmap(SGMap) + geom_point(aes(x = x, y = y, colour = clust), data = industries) +
  ggtitle("Professional services using KMean")
#plot clusters
plot(xy, col=km$cluster, pch = 20)

```

