---
title: "Quadrat analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
packages = c('rgdal', 'maptools', 'spatstat', 'sf') 
for (p in packages){ 
if(!require(p, character.only = T)){ 
install.packages(p) 
} 
library(p,character.only = T) 
} 
```

```{r}
mpsz <- readOGR(dsn = "shp", layer = "MP14_SUBZONE_NO_SEA_PL")
# firms <- readOGR(dsn = "shp", layer = "geocodedCombined")
```

```{r}
industries <- read.csv("data/geocodedCombined.csv", stringsAsFactors = FALSE)
```

```{r}
crs.New <- "+proj=tmerc +lat_0=1.366666666666667 +lon_0=103.8333333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +units=m +no_defs"
industries_shp <- st_as_sf(industries, coords = c("lon","lat"), crs = 4326)
industries_shp <-st_transform(industries_shp, crs = 3414)
industries_sp1 = as(industries_shp, 'Spatial')
industries_sp2 = as(industries_sp1, 'SpatialPoints')
mpsz_svy21 <- spTransform(mpsz, crs.New)
proj4string(mpsz_svy21)
proj4string(industries_sp1)
```
```{r}
legal <- industries_sp1[industries_sp1$type=='Legal', ]
acct <- industries_sp1[industries_sp1$type=='Accountancy', ]
arch <- industries_sp1[industries_sp1$type=='Architectural', ]
bank <- industries_sp1[industries_sp1$type=='Bank', ]
consult <- industries_sp1[industries_sp1$type=='Consultancy', ]
```

```{r}
# mpsz_svy21 <- spTransform(mpsz, CRS("+init=epsg:3414"))
# firms_svy21 <- spTransform(firms, CRS("+init=epsg:3414"))
# ```
# ```{r}
# summary(firms_svy21$type)
# legal <- firms_svy21[firms_svy21$type=='Legal', ]
# acct <- firms_svy21[firms_svy21$type=='Accountancy', ]
# arch <- firms_svy21[firms_svy21$type=='Architectural', ]
# bank <- firms_svy21[firms_svy21$type=='Bank', ]
# consult <- firms_svy21[firms_svy21$type=='Consultancy', ]
```

# cbd just run this for cbd
```{r}
# firms_points <- firms_svy21[mpsz_svy21,]
# firms_points <- remove.duplicates(firms_svy21)
# plot(mpsz_svy21)
# plot(firms_points,col="blue", pch=20, add=T)
# cbd <- mpsz_svy21[mpsz_svy21@data$REGION_N=="CENTRAL REGION",]
# plot(cbd)
# cbd_points <- firms_points[cbd,]
# plot(cbd)
# plot(cbd_points,col="blue", pch=20, add=T)
```
# using csv to run this 
```{r}
firms_points <- industries_sp1[mpsz_svy21,]
firms_points <- remove.duplicates(industries_sp1)
plot(firms_points)
plot(mpsz_svy21)
plot(firms_points,col="blue", pch=20, add=T)
cbd <- mpsz_svy21[mpsz_svy21@data$REGION_N=="CENTRAL REGION",]
plot(cbd)
cbd_points <- firms_points[cbd,]
plot(cbd)
plot(cbd_points,col="blue", pch=20, add=T)
```

# legal
```{r}
  legal_points <- legal[mpsz_svy21,]
  legal_points <- remove.duplicates(legal)
  plot(mpsz_svy21)
  plot(legal_points,col="blue", pch=20, add=T)
  cbd <- mpsz_svy21[mpsz_svy21@data$REGION_N=="CENTRAL REGION",]
  plot(cbd)
  cbd_legal <- legal_points[cbd,]
  plot(cbd)
  plot(cbd_legal,col="blue", pch=20, add=T)
```
#acct
```{r}
  acct_points <- acct[mpsz_svy21,]
  acct_points <- remove.duplicates(acct)
  plot(mpsz_svy21)
  plot(acct_points,col="blue", pch=20, add=T)
  cbd <- mpsz_svy21[mpsz_svy21@data$REGION_N=="CENTRAL REGION",]
  plot(cbd)
  cbd_acct <- acct_points[cbd,]
  plot(cbd)
  plot(cbd_acct,col="blue", pch=20, add=T)
```
#arch
```{r}
  arch_points <- arch[mpsz_svy21,]
  arch_points <- remove.duplicates(arch)
  plot(mpsz_svy21)
  plot(arch_points,col="blue", pch=20, add=T)
  cbd <- mpsz_svy21[mpsz_svy21@data$REGION_N=="CENTRAL REGION",]
  plot(cbd)
  cbd_arch <- arch_points[cbd,]
  plot(cbd)
  plot(cbd_arch,col="blue", pch=20, add=T)
```
#consult
```{r}
  cons_points <- consult[mpsz_svy21,]
  cons_points <- remove.duplicates(consult)
  plot(mpsz_svy21)
  plot(cons_points,col="blue", pch=20, add=T)
  cbd <- mpsz_svy21[mpsz_svy21@data$REGION_N=="CENTRAL REGION",]
  plot(cbd)
 cbd_cons <- cons_points[cbd,]
 plot(cbd)
 plot(cbd_cons,col="blue", pch=20, add=T)
```
#bank 
```{r}
 bank_points <- bank[mpsz_svy21,]
 bank_points <- remove.duplicates(bank)
 plot(mpsz_svy21)
 plot(bank_points,col="blue", pch=20, add=T)
 cbd <- mpsz_svy21[mpsz_svy21@data$REGION_N=="CENTRAL REGION",]
 plot(cbd)
 cbd_bank <- bank_points[cbd,]
 plot(cbd)
 plot(cbd_bank,col="blue", pch=20, add=T)
```

```{r}
window <- as.owin(cbd)
mycolors = c('red','blue','green','orange','violet')
```

# to run quadrat analysis on the number of events
```{r}
cbd_points$type <- factor(cbd_points$type)
levels(cbd_points$type)


firms_ppp <- ppp(x=cbd_points@coords[,1],y=cbd_points@coords[,2], window = window) 
qc <- quadratcount(firms_ppp) 
# qc_10by5 <- quadratcount(firms_ppp, nx = 6, ny = 6) 
  # plot(cbd_bank,pch=16,cex=0.5, col="blue", main="Professional Services in the CBD")
  # plot(cbd_legal,pch=16,cex=0.5, col="green", add=T)
  # plot(cbd_arch,pch=16,cex=0.5, col="green", add=T)
  # plot(cbd_cons,pch=16,cex=0.5, col="green", add=T)
  # plot(cbd_acct,pch=16,cex=0.5, col="green", add=T)
plot(qc,col="red")
plot(cbd_points,pch=1,cex=0.5, col = mycolors, main="Professional Services in the CBD", add=T)

plot(window)

quadrat.test(firms_ppp, method = "M", nsim = 999)
```

#run below for respective firms plot
```{r}
legal_ppp <- ppp(x=legal_points@coords[,1],y=legal_points@coords[,2], window = window)
qc_legal <- quadratcount(legal_ppp, nx = 5, ny = 5) 

plot(qc_legal,col="red")
plot(cbd_legal,pch=16,cex=0.5, add=T)

quadrat.test(legal_ppp, method = "M", nsim = 999)
```

```{r}
acct_ppp <- ppp(x=acct_points@coords[,1],y=acct_points@coords[,2], window = window)
qc_acct <- quadratcount(acct_ppp, nx = 5, ny = 5) 

plot(qc_acct,col="red")
plot(cbd_acct,pch=16,cex=0.5, add=T)

quadrat.test(acct_ppp, method = "M", nsim = 999)
```

```{r}
arch_ppp <- ppp(x=arch_points@coords[,1],y=arch_points@coords[,2], window = window)
qc_arch <- quadratcount(arch_ppp, nx = 5, ny = 5) 

plot(qc_arch,col="red")
plot(cbd_arch,pch=16,cex=0.5, add=T)

quadrat.test(arch_ppp, method = "M", nsim = 999)
```

```{r}
bank_ppp <- ppp(x=bank_points@coords[,1],y=bank_points@coords[,2], window = window)
qc_bank <- quadratcount(bank_ppp, nx = 5, ny = 5) 

plot(qc_bank,col="red")
plot(cbd_bank,pch=16,cex=0.5, add=T)

quadrat.test(bank_ppp, method = "M", nsim = 999)
```

```{r}
cons_ppp <- ppp(x=cons_points@coords[,1],y=cons_points@coords[,2], window = window)
qc_cons <- quadratcount(cons_ppp, nx = 5, ny = 5) 

plot(qc_cons,col="red")
plot(cbd_cons,pch=16,cex=0.5, add=T)

quadrat.test(cons_ppp, method = "M", nsim = 999)
```

